FROM wordpress:php7.1

# Install packages
RUN apt-get update && \
    apt-get -y install vim subversion default-mysql-client less

# Install wp-cli
RUN curl -L -s https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar > /usr/local/bin/wp && chmod +x /usr/local/bin/wp

# Add non-privileged user, best for using wp-cli
RUN groupadd -r user && useradd --no-log-init -r -g user user

# Install phpunit
RUN curl -L -s  https://phar.phpunit.de/phpunit-5.phar > /usr/local/bin/phpunit && chmod +x /usr/local/bin/phpunit

COPY ./install-wp-tests-docker.sh /tmp

RUN /tmp/install-wp-tests-docker.sh latest

# See: https://github.com/docker-library/wordpress/issues/205
COPY ./apache2-custom.sh /usr/local/bin/apache2-custom.sh

COPY ./add-hosts.sh /tmp

CMD ["docker-entrypoint.sh"]
