FROM wordpress:4.7

# No longer including tests and wp-cli in this old version,
# because the base image is so old now that updating its deps is problematic.

# See: https://github.com/docker-library/wordpress/issues/205
COPY ./apache2-custom.sh /usr/local/bin/apache2-custom.sh

COPY ./add-hosts.sh /tmp

CMD ["apache2-foreground"]
