FROM wordpress:5.0-php7.3

# No longer including tests and wp-cli in this old version,
# because the base image is so old now that updating its deps is problematic.

# See: https://github.com/docker-library/wordpress/issues/205
COPY ./apache2-custom.sh /usr/local/bin/apache2-custom.sh

COPY ./add-hosts.sh /tmp

COPY ./disable_auto_update.sh /tmp

RUN /tmp/disable_auto_update.sh

RUN cp -R /usr/src/wordpress/* /var/www/html/

CMD ["apache2-foreground"]
