FROM wordpress:6.0

# Install packages

RUN apt-get update && \
    apt-get -y install vim subversion less

# Install wp-cli
RUN curl -L -s https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar > /usr/local/bin/wp && chmod +x /usr/local/bin/wp

# Add non-privileged user, best for using wp-cli
RUN groupadd -r user && useradd --no-log-init -r -g user user

# Install composer
RUN curl https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer | php -- --quiet && chmod +x composer.phar && mv composer.phar /usr/local/bin/composer

COPY ./install-wp-tests-docker.sh /tmp

RUN /tmp/install-wp-tests-docker.sh 6.0

# Xdebug environment variables
ENV XDEBUG_PORT 9000

# See: https://github.com/docker-library/wordpress/issues/205
COPY ./apache2-custom.sh /usr/local/bin/apache2-custom.sh

COPY ./add-hosts.sh /tmp

COPY ./disable_auto_update.sh /tmp

RUN /tmp/disable_auto_update.sh

RUN cp -R /usr/src/wordpress/* /var/www/html/

CMD ["apache2-foreground"]
