FROM wordpress:latest

# Install packages
RUN apt-get update && \
    apt-get -y install vim subversion default-mysql-client less

# Install wp-cli
RUN curl -L -s https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar > /usr/local/bin/wp && chmod +x /usr/local/bin/wp

# Add non-privileged user, best for using wp-cli
RUN groupadd -r user && useradd --no-log-init -r -g user user

# Install xdebug
RUN pecl install xdebug
# Copy in our php.ini debug configuration
COPY ./docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d

# Install phpunit
RUN curl -L -s  https://phar.phpunit.de/phpunit-7.phar > /usr/local/bin/phpunit && chmod +x /usr/local/bin/phpunit

COPY ./install-wp-tests-docker.sh /tmp

RUN /tmp/install-wp-tests-docker.sh latest

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer require webonyx/graphql-php --ignore-platform-reqs

# Xdebug environment variables
ENV XDEBUG_PORT 9000

# Setup for webpack dev server
COPY ./proxy-webpack-dev.conf /etc/apache2/conf-available
RUN a2enmod proxy
RUN a2enmod proxy_http
RUN a2enconf proxy-webpack-dev

# See: https://github.com/docker-library/wordpress/issues/205
COPY ./apache2-custom.sh /usr/local/bin/apache2-custom.sh

CMD ["apache2-foreground"]
