name: Browser Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [master]

env:
  WORDPRESS_DB_USER: admin
  WORDPRESS_DB_PASSWORD: password
  WORDPRESS_DB_NAME: wordpress
  WP_DOMAIN: localhost:8888
  ENABLE_MOD_SECURITY: false

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Verify Docker is running
        run: |
          echo "Checking Docker status..."
          docker --version
          docker info
          echo "Docker is ready!"

      - name: Start WordPress environment
        run: |
          echo "Starting WordPress environment..."
          docker compose -f docker-compose-ci.yml up -d
          echo "WordPress environment started successfully"

      - name: Wait for WordPress to be ready
        run: |
          timeout=300
          echo "Checking WordPress availability at http://${WP_DOMAIN}..."
          while ! curl -s http://${WP_DOMAIN} > /dev/null; do
            echo "Waiting for WordPress to be ready... (${timeout}s remaining)"
            sleep 5
            timeout=$((timeout - 5))
            if [ $timeout -le 0 ]; then
              echo "WordPress failed to start within 5 minutes"
              echo "Environment status:"
              wp-env status || true
              echo "Environment logs:"
              wp-env logs
              echo "Docker containers:"
              docker ps -a
              exit 1
            fi
          done
          echo "WordPress is ready!"
          echo "Testing admin access..."
          curl -I http://${WP_DOMAIN}/wp-admin/ || echo "Admin not yet accessible"

      - name: Set up WordPress
        run: |
          echo "Setting up WordPress..."
          bin/setup-wordpress.sh

          echo "Activating Font Awesome plugin..."
          docker compose -f docker-compose-ci.yml run --rm wp-cli plugin activate font-awesome

          echo "WordPress setup complete!"

      - name: Install playwright dependencies
        run: |
          cd admin
          sudo npx playwright install-deps
          npx playwright install

      - name: Run Non-Kit Tests on Chrome
        run: cd admin && npm run test:browser-mocked-legacy-cdn-chrome

      - name: Run Pro Kit Tests on Chrome
        run: cd admin && npm run test:browser-mocked-pro-kit-chrome

      - name: Debug on failure
        if: failure()
        run: |
          echo "=== Debug Information ==="
          echo "WordPress site status:"
          curl -I http://${WP_DOMAIN} || echo "Site not accessible"
          echo ""
          echo "WordPress admin status:"
          curl -I http://${WP_DOMAIN}/wp-admin/ || echo "Admin not accessible"
          echo ""
          echo "Plugin status:"
          docker compose -f docker-compose-ci.yml run --rm wp-cli plugin list || echo "Cannot check plugins"
          echo ""
          echo "WordPress version:"
          docker compose -f docker-compose-ci.yml run --rm wp-cli core version || echo "Cannot check WP version"
          echo ""
          echo "Docker containers:"
          docker ps -a || true
          echo ""
          echo "Docker logs for WordPress container:"
          docker logs $(docker ps -q --filter "ancestor=wordpress") || true

      - name: Cleanup
        if: always()
        run: |
          docker compose -f docker-compose-ci.yml down || true
